### PR TITLE
Add link to screenshots

### LINKED ISSUE #83: Include link to screenshot in Twig report
Currently the Twig report does not include a link to the screenshot.

### PR DESCRIPTION
**Pull request by cyberwolf**
Based on #77, refactored away from the hardcoded results/html path.

Fixes #83.

### CODE REVIEW

**Comment by drzraf** [comment]
AFAIU and if `getScreenshotPath()` is usable from Context, this would have the side benefit of simplifying of the implementation.
If currently do this in my FeatureContext:
`$path = $this->params['output_path'] . '/assets/screenshots/' . $featureFolder`
With `output_path` set inside my `__construct(array $parameters)` what in turns requires that I add such a prototype inside `behat.yml`.
Hopefully this complexity could go away.

**Comment by drzraf** [comment]
opened #88

**Comment by rdotter** [comment]
Merged with PR
https://github.com/dutchiexl/BehatHtmlFormatterPlugin/pull/102

**Comment by PurHur** [comment]
This is already merged via a cherry pick or something. Thanks!

**Pull request closed without merging**
