### PR TITLE
#32 Add render options - WP

### PR DESCRIPTION
**Pull request by fonsecas72**
#32 This adds the possibility to set render options like this:

```
render_options: 
     twig_template_name: index.html.twig
     twig_template_path: build/templates
```

The render options can be anything but they must match the attributes of the render.
I did this to add more flexibility.
What do you think?

### CODE REVIEW

**Comment by fonsecas72** [comment]
@dutchiexl sorry the bother but do you have any plans to review this? is it worth the conflict fix?

**Comment by dutchiexl** [comment]
I am so sorry, I completely missed this request.

I would like to make the plugin alot more abstract, where every renderer is a plugin driven by a factory.

**Comment by fonsecas72** [comment]
Ok no problem. I would like to use your Twig renderer and just add or change some stuff. Will your intents allow this? I mean, wouldn't I have to create a new renderer and copy yours would I?

**Comment by PurHur** [comment]
For me this solution is acceptable and a fast usefull way to allow custom templates. 

I will Test this and merge it.

**Pull request closed without merging**
