### PR TITLE
Fix for Issue #103 to change $feature to $scenario

### PR DESCRIPTION
**Pull request by donkidd**
This is to fix the issue reported in
https://github.com/dutchiexl/BehatHtmlFormatterPlugin/issues/103

### CODE REVIEW

**Comment by donkidd** [comment]
Any chance of getting this fix merged?

**Review by rdotter — APPROVED** [review]

**Review by rdotter — APPROVED** [review]

**Review by velpaxl — APPROVED** [review]

**Comment by chadyred** [comment]
@dutchiexl Simple PR

**Comment by goetas** [comment]
I've encountered the same issue, and I confirm that this PR solves the problem. Any chance to see it merged?

**Review by goetas — APPROVED** [review]

**Comment by batigolix** [comment]
PR solves the problem. It can be merged

**Comment by abhiduhan** [comment]
Hi guys, any timeline on when are we getting this fix merged?
Thanks!

**Comment by PurHur** [comment]
Looks good

**Pull request merged**
