### PR TITLE
don't hardcode screenshot path

### PR DESCRIPTION
**Pull request by drzraf**
I don't know why these two 2e543e8 & a49624b appear in the PR

### CODE REVIEW

**Comment by rdotter** [comment]
Merged with PR:
https://github.com/dutchiexl/BehatHtmlFormatterPlugin/pull/102

**Comment by chadyred** [comment]
- [ ] Rebase needed

**Comment by PurHur** [comment]
This PR does include style changes. I would block this PR to the point were a custom template could be loaded?

**Comment by PurHur** [comment]
I reopened #37 for that.

**Comment by PurHur** [comment]
This is actually more than only hardcoding the path. I will fix that in a commit. Do you want the other stuff inside too? I will let this open for some discussion time.

**Pull request closed without merging**
